<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet exclude-result-prefixes="iso map dme xs xd xsl schematron sqf" version="3.0" xmlns="http://purl.oclc.org/dsdl/schematron" xmlns:dme="http://www.mozarteum.at/ns/dme" xmlns:functx="http://www.functx.com" xmlns:iso="http://purl.oclc.org/dsdl/schematron" xmlns:map="http://www.w3.org/2005/xpath-functions/map" xmlns:schematron="http://purl.oclc.org/dsdl/schematron" xmlns:sqf="http://www.schematron-quickfix.com/validator/process" xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">


	<xsl:template name="writeMain">		

			<xsl:comment>Do not edit this file directly! This file is generated automatically by processing  <xsl:value-of select="substring-after(base-uri(/), $base)"/>. If you want to change the rules, edit the corresponding sections 
marked with audience="rules" in the corresponding topic files (*/src/topics/**) or the rules defined in */src/rules/unique_rules.sch.</xsl:comment>

			<schema queryBinding="xslt2" xmlns:sqf="http://www.schematron-quickfix.com/validator/process">
				<ns prefix="mei" uri="http://www.music-encoding.org/ns/mei"/>

				<xsl:call-template name="generatePhases"/>
						
				<xsl:text>&#xA;&#xA;</xsl:text>
				
				<xsl:comment>Abstract rules</xsl:comment>
				<xsl:apply-templates mode="generateIncludes" select="document('../' || $libraryPath)"/>
				
				<xsl:comment>Unique rules</xsl:comment>
				<xsl:for-each select="$unique_rules//schematron:pattern/@id/string()">
					<include href="{concat('unique_rules.sch', '#', .)}"/>
				</xsl:for-each>
				
				<xsl:comment>quickFixes</xsl:comment>
				<include href="quickFix-library.xml"/>
				
				<xsl:apply-templates mode="rules"/>
			</schema>
		
	</xsl:template>
	
	<xsl:include href="generateRules.xsl"/>
	
	
</xsl:stylesheet>
