<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet exclude-result-prefixes="iso map dme xs xd xsl schematron sqf" version="3.0" xmlns="http://purl.oclc.org/dsdl/schematron" xmlns:dme="http://www.mozarteum.at/ns/dme" xmlns:functx="http://www.functx.com" xmlns:iso="http://purl.oclc.org/dsdl/schematron" xmlns:map="http://www.w3.org/2005/xpath-functions/map" xmlns:schematron="http://purl.oclc.org/dsdl/schematron" xmlns:sqf="http://www.schematron-quickfix.com/validator/process" xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	
	
	<xsl:template name="writeMain">
		<xsl:param name="mainPath"/>
		<xsl:param name="base"/>
		<xsl:param name="phases"/>
		<xsl:param as="document-node()" name="docNode"/>
		<xsl:param name="unique_rules"/>
		<xsl:param name="libraryPath"/>
		<xsl:param name="patterns"/>
		
		<xsl:result-document href="rules/main.sch">
			<xsl:comment>Do not edit this file directly! This file is generated automatically by processing  <xsl:value-of select="substring-after(base-uri(/), $base)"/>. If you want to change the rules, edit the corresponding sections 
marked with audience="rules" in the corresponding topic files.</xsl:comment>
			<schema queryBinding="xslt2" xmlns:sqf="http://www.schematron-quickfix.com/validator/process">
				<ns prefix="mei" uri="http://www.music-encoding.org/ns/mei"/>
				<xsl:call-template name="generatePhases">
					<xsl:with-param name="phases" select="$phases"/>
					<xsl:with-param name="docNode" select="$docNode"/>
					<xsl:with-param name="unique_rules" select="$unique_rules"/>
				</xsl:call-template>
				<phase id="refTexts_meiHead">
					<active pattern="work_identifier"/>
				</phase>
				<phase id="altTexts_meiHead">
					<active pattern="work_identifier"/>
				</phase>
				<phase id="checkReferences">
					<active pattern="checkReferences_"/>
				</phase>
				<xsl:apply-templates mode="generateIncludes" select="document('../' || $libraryPath)"/>
				<include href="quickFix-library.xml"/>
				<xsl:for-each select="$patterns">
					<include href="{concat('unique_rules.sch', '#', .)}"/>
				</xsl:for-each>
				<xsl:apply-templates mode="rules"/>
			</schema>
		</xsl:result-document>
	</xsl:template>
	
</xsl:stylesheet>